Dockerise
graze/telnet-client pull request #11
Opened 2018-02-02 16:53 UTC by RokasDevelopment

Dockerised!

2018-02-05 11:08 UTC, biggianteye commented
Builds in travis have failed.

2018-02-12 16:06 UTC, biggianteye requested changes
Looking much better. Just a few more changes.

2018-02-12 16:06 UTC, biggianteye commented on .gitignore
> +
Whitespace

2018-02-12 16:06 UTC, biggianteye commented on Makefile
> +test: test-coverage test-coverage-html test-coverage-clover test-unit test-unit-coverage test-unit-coverage-html test-unit-coverage-clover
There's repeated build targets here. Also, you don't need to do all three versions of coverage. It's the same thing but just different output.

2018-02-12 16:06 UTC, biggianteye commented on docker-compose.yml
> +  php-55:
When running the coverage tests, you'll see that it complains about xdebug not being installed. I would suggest using the `graze/php-alpine` image which is a smaller image containing some of the extra bits that we use. Also the `test` tag contains xdebug.

To maintain the kind of thing being done in this project, I would recommend this which is derived from the skeleton project.

```yaml
  test:
    image: graze/php-alpine:5-test
    volumes:
      - .:/srv
    working_dir: /srv
```

I can talk you through the changes in more detail and the reasoning behind it if you like.

2018-11-05 10:26 UTC, biggianteye approved these changes

2018-11-05 10:26 UTC, merged

2018-11-05 11:21 UTC, john-n-smith commented
👏 👏 👏